CREATE TABLE `chapters` (
	`PK_ChaptersID` int AUTO_INCREMENT NOT NULL,
	`FK_RegionsID` int NOT NULL DEFAULT 0,
	`Code` varchar(50) NOT NULL DEFAULT '',
	`Description` varchar(255) NOT NULL DEFAULT '',
	`FK_UserAccountsID` bigint NOT NULL,
	`EditedBy` bigint NOT NULL,
	`EditedWhen` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`IsRestricted` smallint NOT NULL,
	`IsActive` smallint NOT NULL DEFAULT 1,
	`Stamp` varchar(10) NOT NULL DEFAULT '',
	`Timestamp` timestamp NOT NULL DEFAULT 'current_timestamp()'
);
--> statement-breakpoint
CREATE TABLE `cogs_requests` (
	`PK_RegionsID` bigint AUTO_INCREMENT NOT NULL,
	`FK_UserAccountsID` bigint NOT NULL,
	`EditedWhen` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`Timestamp` timestamp NOT NULL DEFAULT 'current_timestamp()'
);
--> statement-breakpoint
CREATE TABLE `regions` (
	`PK_RegionsID` int AUTO_INCREMENT NOT NULL,
	`FK_AreasID` int NOT NULL DEFAULT 0,
	`Code` varchar(50) NOT NULL DEFAULT '',
	`Description` varchar(255) NOT NULL DEFAULT '',
	`FK_UserAccountsID` bigint NOT NULL,
	`EditedBy` bigint NOT NULL,
	`EditedWhen` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`IsRestricted` smallint NOT NULL,
	`IsActive` smallint NOT NULL DEFAULT 1,
	`Stamp` varchar(10) NOT NULL DEFAULT '',
	`Timestamp` timestamp NOT NULL DEFAULT 'current_timestamp()'
);
--> statement-breakpoint
CREATE TABLE `useraccounts` (
	`PK_UserAccountsID` bigint AUTO_INCREMENT NOT NULL,
	`FK_UserProfilesID` bigint NOT NULL,
	`Username` varchar(100) NOT NULL DEFAULT '',
	`Password` char(128) NOT NULL DEFAULT '',
	`FName` varchar(100) NOT NULL DEFAULT '',
	`LName` varchar(100) NOT NULL DEFAULT '',
	`Email` varchar(100) NOT NULL DEFAULT '',
	`Salt` char(128) NOT NULL DEFAULT '',
	`FK_UserControlID` bigint NOT NULL,
	`FK_UserControlCode` varchar(100) NOT NULL DEFAULT '',
	`AK_UserAccountsType` enum('ADMIN','MEMBER','VIEWER','ENCODER') NOT NULL DEFAULT 'MEMBER',
	`AK_UserAccountsFlag` enum('Approved','Pending') NOT NULL DEFAULT 'Pending',
	`IsMailSent` smallint NOT NULL,
	`FK_UserAccountsID` bigint NOT NULL,
	`EditedBy` bigint NOT NULL,
	`EditedWhen` datetime DEFAULT '1000-01-01 00:00:00',
	`IsRestricted` smallint NOT NULL,
	`IsActive` smallint NOT NULL DEFAULT 1,
	`Stamp` varchar(10) NOT NULL DEFAULT '',
	`Timestamp` timestamp NOT NULL DEFAULT 'current_timestamp()'
);
--> statement-breakpoint
CREATE TABLE `userprofiles` (
	`PK_UserProfilesID` bigint AUTO_INCREMENT NOT NULL,
	`AK_UserProfilesFlag` enum('Deceased','Deleted','For Verification','Pending','Verified') NOT NULL DEFAULT 'For Verification',
	`FK_EventsTagsID` bigint NOT NULL,
	`RFIDNo` varchar(25) NOT NULL DEFAULT '',
	`QRCode` varchar(25) NOT NULL DEFAULT '',
	`LName` varchar(100) NOT NULL DEFAULT '',
	`FName` varchar(100) NOT NULL DEFAULT '',
	`MName` varchar(100) NOT NULL DEFAULT '',
	`Suffix` varchar(100) NOT NULL DEFAULT '',
	`BDate` date NOT NULL DEFAULT '1000-01-01',
	`BPlace` varchar(100) NOT NULL DEFAULT '',
	`Gender` enum('Male','Female') NOT NULL DEFAULT 'Male',
	`CivilStatus` enum('Single','Married','Separated','Widowed') NOT NULL DEFAULT 'Single',
	`Chapter` varchar(100) NOT NULL DEFAULT '',
	`Region` varchar(100) NOT NULL DEFAULT '',
	`Address` varchar(255) NOT NULL DEFAULT '',
	`Barangay` varchar(100) NOT NULL DEFAULT '',
	`FK_RegionID` bigint NOT NULL,
	`FK_CitiesID` bigint NOT NULL,
	`FK_ProvincesID` bigint NOT NULL,
	`FK_CountriesID` bigint NOT NULL,
	`FK_CityID` bigint NOT NULL,
	`FK_ProvID` bigint NOT NULL,
	`ZipCode` varchar(10) NOT NULL DEFAULT '',
	`DupAddress` smallint NOT NULL,
	`Address_M` varchar(255) NOT NULL DEFAULT '',
	`Barangay_M` varchar(100) NOT NULL DEFAULT '',
	`FK_RegionID_M` bigint NOT NULL,
	`FK_CitiesID_M` bigint NOT NULL,
	`FK_ProvincesID_M` bigint NOT NULL,
	`FK_CountriesID_M` bigint NOT NULL,
	`ZipCode_M` varchar(10) NOT NULL DEFAULT '',
	`TelNo` varchar(100) NOT NULL DEFAULT '',
	`Email` varchar(100) NOT NULL DEFAULT '',
	`FaxNo` varchar(100) NOT NULL DEFAULT '',
	`CelNo` varchar(100) NOT NULL DEFAULT '',
	`Province_Bak` varchar(100) NOT NULL DEFAULT '0',
	`City_Bak` varchar(100) NOT NULL DEFAULT '0',
	`Industry` varchar(255) NOT NULL DEFAULT '',
	`Designation` varchar(100) NOT NULL DEFAULT '',
	`Profession` varchar(255) NOT NULL DEFAULT '',
	`Company` varchar(255) NOT NULL DEFAULT '',
	`CompanyAddr` varchar(255) NOT NULL DEFAULT '',
	`CompanyTelNo` varchar(100) NOT NULL DEFAULT '',
	`CompanyFaxNo` varchar(100) NOT NULL DEFAULT '',
	`CompanyCelNo` varchar(100) NOT NULL DEFAULT '',
	`CompanyEmail` varchar(100) NOT NULL DEFAULT '',
	`CompanyWebsite` varchar(100) NOT NULL DEFAULT '',
	`PRCRegNo` varchar(50) NOT NULL DEFAULT '',
	`PRCDateIssued` date NOT NULL DEFAULT '1000-01-01',
	`MemberType` enum('Auxiliary','Associate','Fellow','Life','Regular','Senior','NewMember','NewBoard','Honorary') NOT NULL DEFAULT 'Regular',
	`InsuranceType` enum('Insured','Not Available') NOT NULL DEFAULT 'Not Available',
	`MembershipNo` varchar(50) NOT NULL DEFAULT '0',
	`MembershipDateReg` date NOT NULL DEFAULT '1000-01-01',
	`MembershipValidity` date NOT NULL DEFAULT '1000-01-01',
	`MembershipDateUpdated` date NOT NULL DEFAULT '1000-01-01',
	`FK_TxnVenueID` bigint NOT NULL,
	`ORNo` varchar(25) NOT NULL DEFAULT '',
	`ORDate` date NOT NULL DEFAULT '1000-01-01',
	`ORAmount` decimal(10,2) NOT NULL DEFAULT '0.00',
	`FK_LicenseTypeID` bigint NOT NULL,
	`PRCNo` varchar(50) NOT NULL DEFAULT '',
	`PRCSeqNo` varchar(50) NOT NULL,
	`PRCRegDate` date NOT NULL DEFAULT '1000-01-01',
	`PRCExpDate` date NOT NULL DEFAULT '1000-01-01',
	`Sector` enum('Academe','Government','Private Practice','Private Corporation') NOT NULL,
	`AgreementRFID` smallint NOT NULL,
	`AgreementDPA` smallint NOT NULL,
	`IsDeceased` smallint NOT NULL,
	`IsVIP` smallint NOT NULL,
	`IsEligible` smallint NOT NULL,
	`IsGMM` smallint NOT NULL,
	`IsKIT` smallint NOT NULL,
	`AppType` varchar(100) NOT NULL DEFAULT '',
	`SRCTZN_ID` varchar(50) NOT NULL DEFAULT '',
	`PWD_ID` varchar(50) NOT NULL DEFAULT '',
	`Area` char(50) NOT NULL DEFAULT '',
	`UAPNo` char(50) NOT NULL DEFAULT '',
	`FK_UserAccountsID` bigint NOT NULL,
	`EditedBy` bigint NOT NULL,
	`EditedWhen` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
	`IsRestricted` smallint NOT NULL,
	`IsActive` smallint NOT NULL DEFAULT 1,
	`Stamp` varchar(10) NOT NULL DEFAULT '',
	`Timestamp` timestamp NOT NULL DEFAULT 'current_timestamp()'
);
