DROP TABLE `001_2024_national_election`;--> statement-breakpoint
DROP TABLE `accessgroups`;--> statement-breakpoint
DROP TABLE `areas`;--> statement-breakpoint
DROP TABLE `ballots`;--> statement-breakpoint
DROP TABLE `booths`;--> statement-breakpoint
DROP TABLE `candidates`;--> statement-breakpoint
DROP TABLE `charges`;--> statement-breakpoint
DROP TABLE `cities`;--> statement-breakpoint
DROP TABLE `cities_region`;--> statement-breakpoint
DROP TABLE `competenceareas`;--> statement-breakpoint
DROP TABLE `countries`;--> statement-breakpoint
DROP TABLE `currencies`;--> statement-breakpoint
DROP TABLE `dragonpay`;--> statement-breakpoint
DROP TABLE `duplicatethis`;--> statement-breakpoint
DROP TABLE `election`;--> statement-breakpoint
DROP TABLE `electionimages`;--> statement-breakpoint
DROP TABLE `electioninternal`;--> statement-breakpoint
DROP TABLE `electioninternaltally`;--> statement-breakpoint
DROP TABLE `electionpositions`;--> statement-breakpoint
DROP TABLE `electiontally`;--> statement-breakpoint
DROP TABLE `emailauth`;--> statement-breakpoint
DROP TABLE `emailauth_111224`;--> statement-breakpoint
DROP TABLE `emailauth_112324`;--> statement-breakpoint
DROP TABLE `employment`;--> statement-breakpoint
DROP TABLE `evalcategories`;--> statement-breakpoint
DROP TABLE `evaldetails`;--> statement-breakpoint
DROP TABLE `evaltype`;--> statement-breakpoint
DROP TABLE `events`;--> statement-breakpoint
DROP TABLE `eventsimages`;--> statement-breakpoint
DROP TABLE `eventstags`;--> statement-breakpoint
DROP TABLE `exhibitoraccounts`;--> statement-breakpoint
DROP TABLE `exhibitorevents`;--> statement-breakpoint
DROP TABLE `exhibitorfollowers`;--> statement-breakpoint
DROP TABLE `exhibitorimages`;--> statement-breakpoint
DROP TABLE `exhibitorprofiles`;--> statement-breakpoint
DROP TABLE `fees`;--> statement-breakpoint
DROP TABLE `groupings`;--> statement-breakpoint
DROP TABLE `guestaccounts`;--> statement-breakpoint
DROP TABLE `licensetype`;--> statement-breakpoint
DROP TABLE `loginattempts`;--> statement-breakpoint
DROP TABLE `members`;--> statement-breakpoint
DROP TABLE `members_0618`;--> statement-breakpoint
DROP TABLE `membership`;--> statement-breakpoint
DROP TABLE `membersseries`;--> statement-breakpoint
DROP TABLE `officers`;--> statement-breakpoint
DROP TABLE `orseries`;--> statement-breakpoint
DROP TABLE `otchistory`;--> statement-breakpoint
DROP TABLE `otchistory_copy`;--> statement-breakpoint
DROP TABLE `otcresponse`;--> statement-breakpoint
DROP TABLE `otcseries`;--> statement-breakpoint
DROP TABLE `packages`;--> statement-breakpoint
DROP TABLE `paymentcopy`;--> statement-breakpoint
DROP TABLE `paymententries`;--> statement-breakpoint
DROP TABLE `paymenttrail`;--> statement-breakpoint
DROP TABLE `paymenttrail_copy`;--> statement-breakpoint
DROP TABLE `positions`;--> statement-breakpoint
DROP TABLE `producttype`;--> statement-breakpoint
DROP TABLE `providers`;--> statement-breakpoint
DROP TABLE `provinces`;--> statement-breakpoint
DROP TABLE `reportsqr`;--> statement-breakpoint
DROP TABLE `reportsseries`;--> statement-breakpoint
DROP TABLE `requests`;--> statement-breakpoint
DROP TABLE `schools`;--> statement-breakpoint
DROP TABLE `seminars`;--> statement-breakpoint
DROP TABLE `seminarsdetails`;--> statement-breakpoint
DROP TABLE `seminarssignatory`;--> statement-breakpoint
DROP TABLE `seminarssummary`;--> statement-breakpoint
DROP TABLE `shippingtypes`;--> statement-breakpoint
DROP TABLE `specialization`;--> statement-breakpoint
DROP TABLE `sqlmapfile`;--> statement-breakpoint
DROP TABLE `sqlmapoutput`;--> statement-breakpoint
DROP TABLE `txnvenue`;--> statement-breakpoint
DROP TABLE `useraccounts_111822`;--> statement-breakpoint
DROP TABLE `useraccounts_copy`;--> statement-breakpoint
DROP TABLE `useraccounts_copy040421`;--> statement-breakpoint
DROP TABLE `userattendance`;--> statement-breakpoint
DROP TABLE `usercertificates`;--> statement-breakpoint
DROP TABLE `userchangechapter`;--> statement-breakpoint
DROP TABLE `userchangechapteratch`;--> statement-breakpoint
DROP TABLE `usercontrol`;--> statement-breakpoint
DROP TABLE `usereducation`;--> statement-breakpoint
DROP TABLE `useremails`;--> statement-breakpoint
DROP TABLE `userexpertise`;--> statement-breakpoint
DROP TABLE `userfees`;--> statement-breakpoint
DROP TABLE `userimages`;--> statement-breakpoint
DROP TABLE `userimages_copy`;--> statement-breakpoint
DROP TABLE `userlicense`;--> statement-breakpoint
DROP TABLE `userlicense_copy`;--> statement-breakpoint
DROP TABLE `usermodules`;--> statement-breakpoint
DROP TABLE `userpositions`;--> statement-breakpoint
DROP TABLE `userprofiles_090723`;--> statement-breakpoint
DROP TABLE `userprofiles_111822`;--> statement-breakpoint
DROP TABLE `userprofiles_112824`;--> statement-breakpoint
DROP TABLE `userprofiles_copy`;--> statement-breakpoint
DROP TABLE `userprofiles_copy0728`;--> statement-breakpoint
DROP TABLE `userrequests`;--> statement-breakpoint
DROP TABLE `userrequestsatch`;--> statement-breakpoint
DROP TABLE `userrequeststrail`;--> statement-breakpoint
DROP TABLE `userseminars`;--> statement-breakpoint
DROP TABLE `usersignatures`;--> statement-breakpoint
DROP TABLE `vip`;--> statement-breakpoint
DROP VIEW `view_otc_details`;--> statement-breakpoint
DROP VIEW `view_otc_history`;--> statement-breakpoint
DROP VIEW `view_otc_lastinsertedid`;